[package]
name = "nibi"
version = "0.1.0"
authors = ["suquiya <22910980+suquiya@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
